#!/bin/bash
# =============================================================================
# @file   build-rcdaq
# @author Derek Anderson
# @date   06.05.2025
# -----------------------------------------------------------------------------
# A simple script to build RCDAQ and
# the online-distribution libraries
# ============================================================================

# grab current directory
cwg=$PWD

# set your installation path
ONLINE_MAIN=~/install
if [ ! -z "$1" ] ; then
  ONLINE_MAIN=$1
fi

# set "sphenix" include path
#  - FIXME these will need to get changed upstream sometime soon
export OPT_SPHENIX="$C_INCLUDE_PATH"

# now make build directories
mkdir -p build/rcdaq
mkdir -p build/online_distribution/{eventlibraries,pmonitor}

# build rcdaq
cd build/rcdaq
../../rcdaq/autogen.sh --prefix=$ONLINE_MAIN
make install
cd $cwg

# build event libraries
cd build/online_distribution/eventlibraries
../../../online_distribution/eventlibraries/autogen.sh --prefix=$ONLINE_MAIN
make install
cd $cwg

# build pmonitor
cd build/online_distribution/pmonitor
../../../online_distribution/pmonitor/autogen.sh --prefix=$ONLINE_MAIN
make install
cd $cwg

# end =========================================================================
