#!/bin/bash
# =============================================================================
# @file   switch-to-epic-branch
# @author Derek Anderson
# @date   06.05.2025
# -----------------------------------------------------------------------------
# A simple script to switch relevant repos
# to epic-specific branches
# =============================================================================

cd online_distribution
git checkout -B ePIC
cd -

# end =========================================================================
