#!/bin/bash
# =============================================================================
# @file   unzip-input
# @author Derek Anderson
# @date   06.06.2025
# -----------------------------------------------------------------------------
# A simple script to unzip the tarball
# of example input files
# =============================================================================

# grab current directory
cwd=$PWD

cd ..
tar -zxvf input.tar.gz input/
cd $cwd

# end =========================================================================
